---
- name: Role Assignment Info Play
  hosts: localhost
  gather_facts: false  # not necessary at this time; localhost provides no useful info.
  tasks:
    - name: List Role Assignments at scope
      azure.azcollection.azure_rm_roleassignment:
        assignee_object_id: "{{ az_role_assignment_assignee | default(omit) }}"
        id: "{{ az_role_assignment_id | default(omit) }}"
        name: "{{ az_role_assignment_name | default(omit) }}"
        role_definition_id: "{{ az_role_definition_id | default(omit) }}"
        scope: "{{ az_role_assignment_scope | default(omit) }}"
        state: present
        subscription_id: "{{ az_subscription_id | default(omit) }}"
      register: az_role_assignment
