---
- name: Storage Account List Play
  hosts: localhost
  vars:
    #   ONE of az_subscription_name or id, or neither for default sub.
    #az_subscription_name: 
    #az_subscription_id: 

    #   Optional filters:
    az_resource_group_name: ansible-test-storage-accounts
    #az_resource_group_tags:
    #  - name: keyname
    #    value: keyvalue
  gather_facts: no # not necessary at this time; localhost provides no useful info.
  collections:
    - azure.azcollection
  tasks:
    - name: Gather subscription information
      azure.azcollection.azure_rm_subscription_info:
        name: "{{ az_subscription_name | default(omit) }}"
        id: "{{ az_subscription_id | default(omit) }}"
      register: az_subscriptions
      when: az_subscription_name is defined or az_subscription_id is defined

    - name: Set subscription facts
      set_fact:
        az_subscription_id: "{{ az_subscriptions.subscriptions[0].subscription_id }}"
        az_subscription_name: "{{ az_subscriptions.subscriptions[0].display_name }}"
      when: not az_subscriptions.skipped | default(false)

    - name: Default Storage Account
      azure.azcollection.azure_rm_storageaccount:
        name: "paultaitondefaults"
        account_type: "Standard_LRS"
        resource_group: "{{ az_resource_group_name }}"
        subscription_id: "{{ az_subscription_id | default(omit) }}"
      register: az_storage_account

    - set_fact:
        storage_name_list: "{{ (storage_name_list | default([]) ) | union([az_storage_account.state.name]) }}"

    - name: Storage Account Types
      azure.azcollection.azure_rm_storageaccount:
        name: "ptxa{{ item.name  | lower }}"
        account_type: "{{ item.type | default(omit) }}"
        resource_group: "{{ az_resource_group_name }}"
        subscription_id: "{{ az_subscription_id | default(omit) }}"
        kind: "{{ item.kind | default('StorageV2') }}"
        access_tier: "{{ item.access_tier | default(omit) }}"
      register: az_storage_account
      loop:
        - name: Storage
          kind: Storage
        - kind: StorageV2
          name: StorageV2
        - kind: BlobStorage
          name: BlobStorage
          access_tier: Hot
        - kind: FileStorage
          name: FileStorage
          # type: Premium_LRS
        - kind: BlockBlobStorage
          name: BlockBlobStorage
          # type: Premium_LRS

    - debug:
        var: az_storage_account

    - set_fact:
        storage_name_list: "{{ (storage_name_list | default([]) ) | union(az_storage_account.results | json_query('[*].state.name') ) }}"

    - name: Delete Storage Accounts
      azure.azcollection.azure_rm_storageaccount:
        name: "{{ item }}"
        resource_group: "{{ az_resource_group_name }}"
        state: absent
      loop: "{{ storage_name_list }}"

      # kind: "Storage" dict(type='str', default='StorageV2', choices=['Storage', 'StorageV2', 'BlobStorage', 'FileStorage', 'BlockBlobStorage']),