---
- name: Subscription List
  hosts: localhost
  vars:
  gather_facts: no # not necessary at this time; localhost provides no useful info.
  collections:
    - azure.azcollection
  tasks:
    - name: Gather subscription information
      azure.azcollection.azure_rm_subscription_info:
      register: az_subscriptions

    - name: Set subscription facts
      set_fact:
        az_subscription_id: "{{ az_subscriptions[0].id }}"
        az_subscription_name: "{{ az_subscriptions[0].name }}"
