---
- name: List Managed Disks play
  hosts: localhost
  vars:
    tag_list:
      - appcode:abcd
      - appid:abcd
      #- environment:dev1
      #- hostname:mmull04test01
      #- os:RHEL8-2020.r02
  gather_facts: no # not necessary at this time; localhost provides no useful info.
  collections:
    - azure.azcollection
  tasks:

    - name: List all Managed Disks
      azure.azcollection.azure_rm_manageddisk_info:
      register: az_manageddisks

    - name: Fail for parameters
      azure.azcollection.azure_rm_manageddisk_info:
        name: "{{ az_manageddisks.ansible_info.azure_managed_disk[0].name }}"
      register: failure
      ignore_errors: True

    - name: check for intended failure
      assert:
        that:
          - failure.failed

    - name: List Managed Disks by RG
      azure.azcollection.azure_rm_manageddisk_info:
        resource_group: "{{ az_manageddisks.ansible_info.azure_managed_disk[0].id.split('/')[4] | lower }}"

    - name: List Managed Disks by name
      azure.azcollection.azure_rm_manageddisk_info:
        name: "{{ az_manageddisks.ansible_info.azure_managed_disk[0].name }}"
        resource_group: "{{ az_manageddisks.ansible_info.azure_managed_disk[0].id.split('/')[4] | lower }}"
      ignore_errors: True

#   - name: List Managed Disks by managed_by
#     azure.azcollection.azure_rm_manageddisk_info:
#       managed_by: "{{ az_manageddisks.ansible_info.azure_managed_disk[0].managed_by }}"

    - name: List Managed Disks by tags
      azure.azcollection.azure_rm_manageddisk_info:
        tags: "{{ tag_list }}"
